# Makefile for GapMiner V2
# Phase 1-5: Core modules + Real RPC integration

CC = gcc
# -MMD -MP: emit a .d dependency file per object and track HEADERS.  Without
# this a header-only change (e.g. GPU_ADAPTER_MAX_BATCH 160000 -> 320000 in
# gpu_adapter.h on 2026-09-15) does NOT recompile its users, and stale objects
# silently keep the OLD constant while freshly built callers use the new one.
# That exact mismatch cost the hunt every candidate beyond index 160000 of a
# submit (silent clamp, zero verdicts) until it was found on 2026-09-17.
CFLAGS = -Wall -Wextra -O2 -g -std=c99 -MMD -MP
CFLAGS += $(shell pkg-config --cflags libcurl jansson)
LDFLAGS = -lm -lgmp -lssl -lcrypto
LDFLAGS += $(shell pkg-config --libs libcurl jansson)

# Directories
SRC_DIR = new_src
TEST_DIR = tests
BUILD_DIR = build
BIN_DIR = bin

# Optional CUDA GPU Fermat acceleration (new_src/gpu/gpu_fermat.cu).
# Enable with: make WITH_CUDA=1 [WITH_CGBN_FERMAT=1] [GPU_BITS=2048] [CUDA_ARCH=-arch=sm_86]
# GPU_BITS default (2048 = 32 limbs) covers h256 256 bits + shift 1792 = 2048
# bits, the widest shift CGBN can run at TPI=8: above AL=32 the per-thread limb
# count exceeds the 8-limb half algorithm CGBN implements. The active limb count is
# narrowed at runtime per shift (gpu_adapter_set_candidate_bits), so low
# shifts still run at their actual width (e.g. AL=6 at shift 26) and land on
# CGBN's AL=6/TPI=4 fast path when WITH_CGBN_FERMAT=1. Without WITH_CUDA,
# gpu_adapter.c falls back to the existing CPU (GMP) Fermat test unchanged.
GPU_BITS ?= 2048
GPU_NLIMBS := $(shell echo '$(GPU_BITS) / 64' | bc)

ifdef WITH_CUDA
NVCC ?= nvcc
CUDA_ARCH ?= -arch=sm_86
# Auto-detect the CUDA toolkit: prefer /usr/local/cuda, else the distro
# system install (headers in /usr/include, libcudart in /usr/lib/x86_64-linux-gnu).
CUDA_PATH ?= $(shell test -d /usr/local/cuda && echo /usr/local/cuda || echo /usr)
CUDA_LIBDIR ?= $(shell test -d /usr/local/cuda/lib64 && echo /usr/local/cuda/lib64 || echo /usr/lib/x86_64-linux-gnu)
CFLAGS += -DWITH_CUDA -DGPU_NLIMBS=$(GPU_NLIMBS) -I$(CUDA_PATH)/include
NVCC_FLAGS = -DGPU_NLIMBS=$(GPU_NLIMBS) -std=c++17 -MMD -MP
LDFLAGS += -lcudart -L$(CUDA_LIBDIR)

# Optional CGBN-based Fermat kernel (~1.9x faster for even active-limb widths).
# Requires internet on first build (auto-clones NVlabs/CGBN header-only library).
CGBN_DIR := tools/cgbn
CGBN_HDR := $(CGBN_DIR)/include/cgbn/cgbn.h
ifdef WITH_CGBN_FERMAT
NVCC_FLAGS += -DWITH_CGBN_FERMAT -I$(CGBN_DIR)/include
CFLAGS += -DWITH_CGBN_FERMAT
endif

GPU_OBJ = $(BUILD_DIR)/$(SRC_DIR)/gpu/gpu_fermat.o \
		  $(BUILD_DIR)/$(SRC_DIR)/gpu/gpu_sieve.o
else
GPU_OBJ =
endif

# Source files
SOURCES = $(SRC_DIR)/sieve_core.c \
          $(SRC_DIR)/gap_detection.c \
          $(SRC_DIR)/gap_dist.c \
          $(SRC_DIR)/halfclass.c \
          $(SRC_DIR)/primality_fermat.c \
          $(SRC_DIR)/primality_euler.c \
          $(SRC_DIR)/primality_bpsw.c \
          $(SRC_DIR)/primality_limbs.c \
          $(SRC_DIR)/atomic_nonce.c \
          $(SRC_DIR)/gap_priority.c \
          $(SRC_DIR)/crt_set.c \
          $(SRC_DIR)/gap_target.c \
          $(SRC_DIR)/pow_q48.c \
          $(SRC_DIR)/covering.c \
          $(SRC_DIR)/crt_runtime.c \
          $(SRC_DIR)/worker_gpu.c \
          $(SRC_DIR)/miner_farm.c \
          $(SRC_DIR)/gpu_adapter.c \
          $(SRC_DIR)/gapcoin_rpc.c \
		  $(SRC_DIR)/gapcoin_work.c \
          $(SRC_DIR)/block_assembly.c \
          $(SRC_DIR)/submission_pipeline.c \
          $(SRC_DIR)/merit_records.c \
          $(SRC_DIR)/record_log.c \
          $(SRC_DIR)/gap_hunt.c \
          $(SRC_DIR)/stratum.c

OBJECTS = $(SOURCES:%.c=$(BUILD_DIR)/%.o) $(GPU_OBJ)
# Header dependencies generated by -MMD -MP (see CFLAGS).  `find` at parse time
# keeps this self-maintaining for every object (sources, gpu, tests).
-include $(shell find $(BUILD_DIR) -name '*.d' 2>/dev/null)

# Main binary and tests
MAIN_BINARY = $(BIN_DIR)/gapminer
TEST_GAP_DETECTION = $(BIN_DIR)/test_gap_detection
TEST_PRIMALITY = $(BIN_DIR)/test_primality
TEST_WORKER_THREADS = $(BIN_DIR)/test_worker_threads
TEST_GAPCOIN_RPC = $(BIN_DIR)/test_gapcoin_rpc
TEST_BLOCK_SUBMISSION = $(BIN_DIR)/test_block_submission
TEST_SIEVE_CORE = $(BIN_DIR)/test_sieve_core
TEST_GPU_FERMAT = $(BIN_DIR)/test_gpu_fermat
TEST_GPU_SIEVE = $(BIN_DIR)/test_gpu_sieve
TEST_GPU_RESOLVE = $(BIN_DIR)/test_gpu_resolve
TEST_RUN_PROFILE = $(BIN_DIR)/test_run_profile
TEST_GAP_DIST = $(BIN_DIR)/test_gap_dist
TEST_HALFCLASS = $(BIN_DIR)/test_halfclass
TEST_GAP_PRIORITY = $(BIN_DIR)/test_gap_priority
TEST_CRT_SET = $(BIN_DIR)/test_crt_set
CRT_GEN = $(BIN_DIR)/crt_gen
TEST_GAP_TARGET = $(BIN_DIR)/test_gap_target
TEST_POW_Q48 = $(BIN_DIR)/test_pow_q48
TEST_COVERING = $(BIN_DIR)/test_covering
GEN_CRT = $(BIN_DIR)/gen_crt
TEST_CRT_RUNTIME = $(BIN_DIR)/test_crt_runtime
TEST_CRT_SUBMISSION = $(BIN_DIR)/test_crt_submission
TEST_GAP_HUNT = $(BIN_DIR)/test_gap_hunt
TEST_STRATUM = $(BIN_DIR)/test_stratum
BENCH_FERMAT = $(BIN_DIR)/bench_fermat
BENCH_MARK = $(BIN_DIR)/bench_mark
BENCH_HUNT_MARK = $(BIN_DIR)/bench_hunt_mark
BENCH_P0SIEVE = $(BIN_DIR)/bench_p0sieve
CUDA_INT = $(BIN_DIR)/cuda_int_throughput
COVER_MAX = $(BIN_DIR)/cover_max
PHASE0_SCAN = $(BIN_DIR)/phase0_scan
PHASE0_SCAN_GPU = $(BIN_DIR)/phase0_scan_gpu
MR68_GPU = $(BIN_DIR)/mr68_gpu
MR128_BENCH = $(BIN_DIR)/mr128_bench

# Phony targets
.PHONY: all clean test help update-merits

# Default target
all: $(BIN_DIR) $(BUILD_DIR) $(OBJECTS) $(MAIN_BINARY) $(TEST_GAP_DETECTION) $(TEST_PRIMALITY) $(TEST_WORKER_THREADS) $(TEST_GAPCOIN_RPC) $(TEST_BLOCK_SUBMISSION) $(TEST_SIEVE_CORE) $(TEST_GPU_FERMAT) $(TEST_GPU_SIEVE) $(TEST_GPU_RESOLVE) $(TEST_GAP_DIST) $(TEST_HALFCLASS) $(TEST_GAP_PRIORITY) $(TEST_CRT_SET) $(TEST_GAP_TARGET) $(TEST_POW_Q48) $(TEST_COVERING) $(TEST_CRT_RUNTIME) $(TEST_CRT_SUBMISSION) $(TEST_GAP_HUNT) $(TEST_STRATUM) $(CRT_GEN) $(GEN_CRT) $(COVER_MAX)

# CUDA-only dev tool, not part of the default build: make bin/bench_mark WITH_CUDA=1

# Create directories
$(BIN_DIR):
	@mkdir -p $(BIN_DIR)

$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/$(SRC_DIR)
	@mkdir -p $(BUILD_DIR)/$(TEST_DIR)

# Compile source files
$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Link main binary
$(MAIN_BINARY): $(OBJECTS) $(BUILD_DIR)/$(SRC_DIR)/main.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Link test_gap_detection
$(TEST_GAP_DETECTION): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_gap_detection.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -o $@
	@echo "✓ Built: $@"

# Link test_primality
$(TEST_PRIMALITY): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_primality.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -o $@
	@echo "✓ Built: $@"

# Link test_worker_threads
$(TEST_WORKER_THREADS): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_worker_threads.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Link test_gapcoin_rpc
$(TEST_GAPCOIN_RPC): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_gapcoin_rpc.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Link test_block_submission
$(TEST_BLOCK_SUBMISSION): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_block_submission.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

$(TEST_SIEVE_CORE): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_sieve_core.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Link test_gpu_fermat (self-skips at runtime when built without WITH_CUDA=1)
$(TEST_GPU_FERMAT): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_gpu_fermat.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Link test_gpu_sieve (self-skips at runtime when built without WITH_CUDA=1)
$(TEST_GPU_SIEVE): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_gpu_sieve.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Link test_gpu_resolve (GPU hidden-resolution exactness; self-skips without CUDA)
$(TEST_GPU_RESOLVE): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_gpu_resolve.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Link test_gap_dist
$(TEST_GAP_DIST): $(BUILD_DIR)/$(SRC_DIR)/gap_dist.o $(BUILD_DIR)/$(TEST_DIR)/test_gap_dist.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -o $@
	@echo "✓ Built: $@"

# Runtime run-profile tool (survivor constellation of a CRT file)
$(TEST_RUN_PROFILE): $(BUILD_DIR)/$(SRC_DIR)/crt_runtime.o $(BUILD_DIR)/$(TEST_DIR)/test_run_profile.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -o $@
	@echo "✓ Built: $@"

# Link test_halfclass (HALF_CLASS two-pass parity vs the full-class pipeline)
$(TEST_HALFCLASS): $(BUILD_DIR)/$(SRC_DIR)/halfclass.o $(BUILD_DIR)/$(SRC_DIR)/gap_detection.o $(BUILD_DIR)/$(SRC_DIR)/gap_dist.o $(BUILD_DIR)/$(SRC_DIR)/sieve_core.o $(BUILD_DIR)/$(TEST_DIR)/test_halfclass.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# GPU Fermat kernel throughput benchmark (dev tool)
$(BENCH_FERMAT): $(OBJECTS) $(BUILD_DIR)/tools/bench_fermat.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Dedicated 68-bit-class Miller-Rabin kernel for the Phase-0 exhaustive scan
# (standalone CUDA TU; no gapminer/gap_hunt objects; GMP is linked host-side
# ONLY for the --validate gate against mpz_probab_prime_p).
$(MR68_GPU): $(BUILD_DIR)/tools/mr68_gpu.o | $(BIN_DIR)
	$(NVCC) $(BUILD_DIR)/tools/mr68_gpu.o -L$(CUDA_LIBDIR) -lcudart -lgmp -lm -o $@
	@echo "✓ Built: $@"

# 128-bit walk-engine primality test: GMP cross-check (--validate) + benchmark
# of the production kernel and its experimental faster variants.
# Build: make bin/mr128_bench WITH_CUDA=1
$(MR128_BENCH): $(BUILD_DIR)/tools/mr128_bench.o | $(BIN_DIR)
	$(NVCC) $(BUILD_DIR)/tools/mr128_bench.o -L$(CUDA_LIBDIR) -lcudart -lgmp -lm -o $@
	@echo "✓ Built: $@"

# GPU live Phase-0 scanner: CPU bucketed sieve + the shared mr68 kernel;
# GMP host-side for --check and for verifying every reported gap.
# Build: make bin/phase0_scan_gpu WITH_CUDA=1
$(PHASE0_SCAN_GPU): $(BUILD_DIR)/tools/phase0_scan_gpu.o | $(BIN_DIR)
	$(NVCC) $(BUILD_DIR)/tools/phase0_scan_gpu.o -L$(CUDA_LIBDIR) -lcudart -lgmp -lm -lpthread -o $@
	@echo "✓ Built: $@"

# Split-mode build of the same scanner (Linux gate for the Windows kernel-DLL
# architecture of README_WINDOWS.md): tools/phase0gpu_dll.o is the DLL
# translation unit (the exact source windows\build_phase0.bat compiles with
# nvcc+MSVC), linked against the host TU compiled as C++ with
# -DPHASE0_KERNEL_DLL.  A fixed-range walk/sieve run of this binary must be
# byte-identical to bin/phase0_scan_gpu (README_PHASE0.md, gates).
PHASE0_SCAN_GPU_SPLIT = $(BIN_DIR)/phase0_scan_gpu_split

$(PHASE0_SCAN_GPU_SPLIT): $(BUILD_DIR)/tools/phase0_scan_gpu_hdll.o $(BUILD_DIR)/tools/phase0gpu_dll.o | $(BIN_DIR)
	$(CXX) $^ -L$(CUDA_LIBDIR) -lcudart -lgmp -lm -lpthread -o $@
	@echo "✓ Built: $@"

$(BUILD_DIR)/tools/phase0_scan_gpu_hdll.o: tools/phase0_scan_gpu.cu tools/phase0gpu_api.h tools/p0_types.h
	@mkdir -p $(dir $@)
	$(CXX) -x c++ -O2 -std=gnu++17 -MMD -MP -DPHASE0_KERNEL_DLL -Itools -c $< -o $@

# Per-kernel cost split of the --gap-hunt window MARK at production geometry
# (dev tool, CUDA only; includes gpu_sieve.cu so it drives the real kernels).
$(BENCH_HUNT_MARK): $(BUILD_DIR)/tools/bench_hunt_mark.o | $(BIN_DIR)
	$(NVCC) $(BUILD_DIR)/tools/bench_hunt_mark.o -L$(CUDA_LIBDIR) -lcudart -lm -o $@
	@echo "✓ Built: $@"

# GPU bitmap-mark kernel cost-model microbenchmark (dev tool, CUDA only).
# Standalone TU (does not link the miner objects); needs nvcc.
$(BENCH_MARK): $(BUILD_DIR)/tools/bench_mark.o | $(BIN_DIR)
	$(NVCC) $(BUILD_DIR)/tools/bench_mark.o -L$(CUDA_LIBDIR) -lcudart -lm -o $@
	@echo "✓ Built: $@"

# GPU bitmap-marking probe for the live Phase-0 scanner geometry (dev tool):
# measures the full per-segment GPU cycle (memset + mark kernel + D2H of the
# 64 KB bitmap) and verifies segment bitmaps against a naive CPU marker.
# Build: make bin/bench_p0sieve WITH_CUDA=1
$(MR128_BENCH): $(BUILD_DIR)/tools/mr128_bench.o tools/mr128_kernel.cuh | $(BIN_DIR)
	$(NVCC) $(BUILD_DIR)/tools/mr128_bench.o -L$(CUDA_LIBDIR) -lcudart -lgmp -lm -o $@
	@echo "✓ Built: $@"

$(BENCH_P0SIEVE): $(BUILD_DIR)/tools/bench_p0sieve.o | $(BIN_DIR)
	$(NVCC) $(BUILD_DIR)/tools/bench_p0sieve.o -L$(CUDA_LIBDIR) -lcudart -lm -o $@
	@echo "✓ Built: $@"

# GPU integer-arithmetic ceiling microbenchmark (dev tool, CUDA only): the
# retire rates of IMAD / 64-bit mul / mul64hi / __dp4a / int8 m16n8k16, each
# cross-checked against wall clock and (by hand) against the device limits.
# Feeds scripts/arith_ceiling.py.  Build: make bin/cuda_int_throughput WITH_CUDA=1
$(CUDA_INT): $(BUILD_DIR)/tools/cuda_int_throughput.o | $(BIN_DIR)
	$(NVCC) $(BUILD_DIR)/tools/cuda_int_throughput.o -L$(CUDA_LIBDIR) -lcudart -lm -o $@
	@echo "✓ Built: $@"

$(BUILD_DIR)/tools/%.o: tools/%.cu | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(NVCC) -O3 $(CUDA_ARCH) -std=c++17 -Xcompiler -O2 -I$(SRC_DIR)/gpu -c $< -o $@

$(BUILD_DIR)/tools/mr68_gpu.o: tools/mr68_kernel.cuh
$(BUILD_DIR)/tools/phase0_scan_gpu.o: tools/mr68_kernel.cuh tools/perig.cuh \
    tools/p0_mark.cuh tools/p0_types.h tools/p0_walk_kern.cuh tools/phase0gpu_api.h
$(BUILD_DIR)/tools/bench_p0sieve.o: tools/p0_mark.cuh tools/p0_types.h
$(BUILD_DIR)/tools/phase0gpu_dll.o: tools/phase0gpu_api.h tools/mr68_kernel.cuh \
    tools/p0_mark.cuh tools/p0_types.h tools/p0_walk_kern.cuh tools/perig.cuh

# Link test_gap_priority
$(TEST_GAP_PRIORITY): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_gap_priority.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# CRT set module (lightweight: only crt_set.o + its consumer, no CUDA needed)
$(TEST_CRT_SET): $(BUILD_DIR)/$(SRC_DIR)/crt_set.o $(BUILD_DIR)/$(TEST_DIR)/test_crt_set.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

$(CRT_GEN): $(BUILD_DIR)/$(SRC_DIR)/crt_set.o $(BUILD_DIR)/$(SRC_DIR)/crt_gen_main.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

$(GEN_CRT): $(BUILD_DIR)/$(SRC_DIR)/covering.o $(BUILD_DIR)/$(SRC_DIR)/gen_crt_main.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ -lm -o $@
	@echo "✓ Built: $@"

# Covering-coverage search experiment tool (GPA-style; CPU-only dev tool)
$(COVER_MAX): $(BUILD_DIR)/$(SRC_DIR)/covering.o $(BUILD_DIR)/tools/cover_max.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ -lm -o $@
	@echo "✓ Built: $@"

# Phase-0 exhaustive prime-gap scan prototype (CPU reference; GMP + pthreads)
$(PHASE0_SCAN): $(BUILD_DIR)/tools/phase0_scan.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ -lm -lgmp -lpthread -o $@
	@echo "✓ Built: $@"

$(TEST_CRT_RUNTIME): $(BUILD_DIR)/$(SRC_DIR)/covering.o $(BUILD_DIR)/$(SRC_DIR)/crt_runtime.o $(BUILD_DIR)/$(TEST_DIR)/test_crt_runtime.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ -lm -lgmp -o $@
	@echo "✓ Built: $@"

# CRT big-nAdd submission assembly (links the full object set like the other
# integration tests; CPU-only in `make test`).
$(TEST_CRT_SUBMISSION): $(OBJECTS) $(BUILD_DIR)/$(TEST_DIR)/test_crt_submission.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

$(TEST_GAP_TARGET): $(BUILD_DIR)/$(SRC_DIR)/gap_target.o $(BUILD_DIR)/$(TEST_DIR)/test_gap_target.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

$(TEST_POW_Q48): $(BUILD_DIR)/$(SRC_DIR)/pow_q48.o $(BUILD_DIR)/$(TEST_DIR)/test_pow_q48.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

$(TEST_COVERING): $(BUILD_DIR)/$(SRC_DIR)/covering.o $(BUILD_DIR)/$(TEST_DIR)/test_covering.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lm -o $@
	@echo "✓ Built: $@"

# GAP_HUNT record validator (CPU-only: nextprime exactness over an out file)
$(TEST_GAP_HUNT): $(BUILD_DIR)/$(SRC_DIR)/primality_bpsw.o $(BUILD_DIR)/$(TEST_DIR)/test_gap_hunt.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ -lm -lgmp -o $@
	@echo "✓ Built: $@"

# Gapcoin legacy stratum client (mock pool server, no network needed)
$(TEST_STRATUM): $(BUILD_DIR)/$(SRC_DIR)/stratum.o $(BUILD_DIR)/$(TEST_DIR)/test_stratum.o | $(BIN_DIR)
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -lpthread -o $@
	@echo "✓ Built: $@"

# Compile test objects
$(BUILD_DIR)/$(TEST_DIR)/%.o: $(TEST_DIR)/%.c
	@mkdir -p $(BUILD_DIR)/$(TEST_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Compile dev tools
$(BUILD_DIR)/tools/%.o: tools/%.c
	@mkdir -p $(BUILD_DIR)/tools
	$(CC) $(CFLAGS) -I$(SRC_DIR) -c $< -o $@

# Compile CUDA GPU sources (only reached when WITH_CUDA=1 selects a .o under gpu/)
$(BUILD_DIR)/$(SRC_DIR)/gpu/%.o: $(SRC_DIR)/gpu/%.cu | $(BUILD_DIR)
	@mkdir -p $(dir $@)
ifdef WITH_CGBN_FERMAT
	@if [ ! -f "$(CGBN_HDR)" ]; then \
		echo "[cgbn] Cloning NVlabs/CGBN (header-only)..."; \
		git clone --depth=1 https://github.com/NVlabs/CGBN.git $(CGBN_DIR); \
	fi
endif
	$(NVCC) -O3 $(CUDA_ARCH) $(NVCC_FLAGS) -c $< -o $@

# Run tests
test: $(TEST_GAP_DETECTION) $(TEST_PRIMALITY) $(TEST_WORKER_THREADS) $(TEST_GAPCOIN_RPC) $(TEST_BLOCK_SUBMISSION) $(TEST_SIEVE_CORE) $(TEST_GPU_FERMAT) $(TEST_GPU_SIEVE) $(TEST_GPU_RESOLVE) $(TEST_GAP_DIST) $(TEST_HALFCLASS) $(TEST_GAP_PRIORITY) $(TEST_CRT_SET) $(TEST_GAP_TARGET) $(TEST_POW_Q48) $(TEST_COVERING) $(TEST_CRT_RUNTIME) $(TEST_CRT_SUBMISSION) $(TEST_STRATUM)
	@echo "\n========== Running Integration Tests =========="
	@$(TEST_GAP_DETECTION)
	@echo ""
	@$(TEST_PRIMALITY)
	@echo ""
	@$(TEST_WORKER_THREADS)
	@echo ""
	@$(TEST_GAPCOIN_RPC)
	@echo ""
	@$(TEST_BLOCK_SUBMISSION)
	@echo ""
	@$(TEST_SIEVE_CORE)
	@echo ""
	@$(TEST_GPU_FERMAT)
	@echo ""
	@$(TEST_GPU_SIEVE)
	@echo ""
	@$(TEST_GAP_DIST)
	@echo ""
	@$(TEST_HALFCLASS)
	@echo ""
	@$(TEST_GAP_PRIORITY)
	@echo ""
	@$(TEST_CRT_SET)
	@echo ""
	@$(TEST_GAP_TARGET)
	@echo ""
	@$(TEST_POW_Q48)
	@echo ""
	@$(TEST_COVERING)
	@echo ""
	@$(TEST_CRT_RUNTIME)
	@echo ""
	@$(TEST_CRT_SUBMISSION)
	@echo ""
	@$(TEST_STRATUM)

# Clean build artifacts
clean:
	@rm -rf $(BUILD_DIR) $(BIN_DIR)
	@echo "✓ Cleaned build artifacts"

# Refresh data/prime_gap_merits.txt from primegaps.cloudygo.com (requires internet)
update-merits:
	@bash scripts/update_merits.sh

# Help
help:
	@echo "GapMiner V2 — Phase 1 Makefile"
	@echo ""
	@echo "Targets:"
	@echo "  all             - Build all object files and test binaries"
	@echo "  test            - Run integration tests"
	@echo "  clean           - Remove build artifacts"
	@echo "  update-merits   - Refresh data/prime_gap_merits.txt from primegaps.cloudygo.com"
	@echo "  help            - Show this help message"
	@echo ""
	@echo "Example: make test"
