/*
 * Test: Gapcoin Q48 arithmetic and certified interval rejection
 * (new_src/pow_q48.{h,c}).
 *
 * Verifies:
 *   1. Bit-exactness against tests/data/pow_q48_vectors.txt, which was
 *      generated by linking the *node's* PoWUtils.cpp (tools/pow_q48_oracle.cpp
 *      + scripts/gen_pow_q48_vectors.sh): merit, rand, difficulty,
 *      target_size and the accept/reject verdict must all agree exactly.
 *   2. min_gap_distance_merit matches its closed form 2*2^48/ln(start).
 *   3. The rejection certificate is sound: whenever it claims a span cannot
 *      reach the target, the exact node arithmetic must not accept it.
 *   4. Fail-open semantics: no target / degenerate input -> UNKNOWN, and a
 *      0 bound never rejects anything.
 *   5. The header helper reads the template nDifficulty the way the node
 *      writes it.
 *   6. Boundary cases where merit is *below* the target but rand() lifts the
 *      difficulty above it -- the case a merit-only gate drops.
 *
 * Usage: ./bin/test_pow_q48 [vectors-file]
 */

#include "../new_src/pow_q48.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_START_HEX 600

static int failures = 0;

static void fail(const char *what, const char *detail) {
    fprintf(stderr, "FAIL: %s (%s)\n", what, detail ? detail : "");
    failures++;
}

/* ln(n) as a double without mpz_get_d() overflow (n may exceed 2^1024). */
static double ln_mpz_double(const mpz_t n) {
    signed long exp = 0;
    double mant;

    if (mpz_sgn(n) <= 0) return 0.0;
    mant = mpz_get_d_2exp(&exp, n);
    return log(mant) + (double)exp * log(2.0);
}

/* ---------------------------------------------------------------------------
 * 1. Vector comparison
 * ------------------------------------------------------------------------- */

static int test_vectors(const char *path) {
    FILE *f = fopen(path, "r");
    char start_hex[MAX_START_HEX];
    unsigned long long gap, target, exp_merit, exp_rand, exp_diff, exp_ts;
    int exp_valid;
    int cases = 0, accepted = 0, rejected = 0;
    int lifted = 0;              /* valid although merit < target */
    int crlf = 0;

    if (!f) {
        fprintf(stderr, "FAIL: cannot open vectors '%s'"
                        " (run scripts/gen_pow_q48_vectors.sh)\n", path);
        failures++;
        return 0;
    }

    while (fscanf(f, " %599s", start_hex) == 1) {
        int got;

        if (start_hex[0] == '#') {
            /* skip the rest of the comment line */
            int c;
            while ((c = fgetc(f)) != EOF && c != '\n') { /* skip */ }
            continue;
        }

        got = fscanf(f, " %llx %llx %llx %llx %llx %llx %d",
                     &gap, &target, &exp_merit, &exp_rand, &exp_diff,
                     &exp_ts, &exp_valid);
        if (got != 7) {
            fprintf(stderr, "FAIL: malformed vector line after '%s' (%d fields)\n",
                    start_hex, got);
            failures++;
            break;
        }

        mpz_t start, end;
        mpz_inits(start, end, NULL);
        if (mpz_set_str(start, start_hex, 16) != 0) {
            fail("vector start parse", start_hex);
            mpz_clears(start, end, NULL);
            continue;
        }
        mpz_add_ui(end, start, (uint64_t)gap);

        uint64_t merit = pow_q48_merit(start, end);
        uint64_t rnd = pow_q48_rand(start, end);
        uint64_t diff = pow_q48_difficulty(start, end);
        uint64_t ts = pow_q48_target_size(start, (uint64_t)target);
        pow_q48_verdict verdict =
            pow_q48_classify(start, end, (uint64_t)target);

        if (merit != (uint64_t)exp_merit) {
            char d[160];
            snprintf(d, sizeof(d), "start=%.32s gap=%llu ours=%llx node=%llx",
                     start_hex, gap, (unsigned long long)merit, exp_merit);
            fail("merit != node", d);
        }
        if (rnd != (uint64_t)exp_rand) {
            char d[160];
            snprintf(d, sizeof(d), "start=%.32s gap=%llu ours=%llx node=%llx",
                     start_hex, gap, (unsigned long long)rnd, exp_rand);
            fail("rand != node", d);
        }
        if (diff != (uint64_t)exp_diff) {
            char d[160];
            snprintf(d, sizeof(d), "start=%.32s gap=%llu ours=%llx node=%llx",
                     start_hex, gap, (unsigned long long)diff, exp_diff);
            fail("difficulty != node", d);
        }
        if (ts != (uint64_t)exp_ts) {
            char d[160];
            snprintf(d, sizeof(d), "start=%.32s target=%llx ours=%llx node=%llx",
                     start_hex, target, (unsigned long long)ts, exp_ts);
            fail("target_size != node", d);
        }
        if ((verdict == POW_Q48_ACCEPT) != (exp_valid != 0)) {
            char d[160];
            snprintf(d, sizeof(d), "start=%.32s gap=%llu verdict=%d node_valid=%d",
                     start_hex, gap, (int)verdict, exp_valid);
            fail("verdict != node valid()", d);
        }

        if (exp_valid) {
            accepted++;
            if ((uint64_t)exp_merit < (uint64_t)target) lifted++;
        } else {
            rejected++;
        }
        cases++;

        mpz_clears(start, end, NULL);
    }

    fclose(f);
    (void)crlf;

    if (cases < 50) {
        char d[96];
        snprintf(d, sizeof(d), "only %d vectors parsed", cases);
        fail("vector count", d);
        return cases;
    }

    printf("  vectors: %d (node accepts %d, rejects %d)\n",
           cases, accepted, rejected);
    printf("  acceptances where merit < target (rand lifted): %d\n", lifted);
    if (lifted == 0) {
        fail("boundary coverage", "no vector where rand lifts merit below target");
    }
    return cases;
}

/* ---------------------------------------------------------------------------
 * 2. min_gap_distance_merit closed form
 * ------------------------------------------------------------------------- */

static void test_min_gap_closed_form(void) {
    static const unsigned kBits[] = {256, 512, 1024, 2048};
    gmp_randstate_t rs;

    gmp_randinit_mt(rs);
    gmp_randseed_ui(rs, 424242u);

    for (unsigned w = 0; w < sizeof(kBits) / sizeof(kBits[0]); w++) {
        unsigned bits = kBits[w];
        for (int c = 0; c < 8; c++) {
            mpz_t start;
            mpz_init(start);
            mpz_urandomb(start, rs, bits);
            mpz_setbit(start, bits - 1);
            mpz_setbit(start, 0);

            uint64_t m2 = pow_q48_min_gap_merit(start);
            double expected = 2.0 * ((double)POW_Q48_ONE) / ln_mpz_double(start);

            if (fabs((double)m2 - expected) > 2.0) {
                char d[160];
                snprintf(d, sizeof(d), "bits=%u ours=%llu expected=%.3f",
                         bits, (unsigned long long)m2, expected);
                fail("min_gap_merit closed form", d);
            }
            if (m2 == 0) fail("min_gap_merit must never be 0 (modulus)", NULL);

            mpz_clear(start);
        }
    }
    gmp_randclear(rs);
}

/* ---------------------------------------------------------------------------
 * 3. Certificate soundness (property test)
 * ------------------------------------------------------------------------- */

static void test_certificate_soundness(void) {
    static const unsigned kBits[] = {64, 256, 512, 1024, 2048};
    gmp_randstate_t rs;
    int certified = 0, examined = 0;

    gmp_randinit_mt(rs);
    gmp_randseed_ui(rs, 777001u);

    for (unsigned w = 0; w < sizeof(kBits) / sizeof(kBits[0]); w++) {
        unsigned bits = kBits[w];
        for (int c = 0; c < 6; c++) {
            mpz_t start, end, bound;
            mpz_inits(start, end, bound, NULL);
            mpz_urandomb(start, rs, bits);
            mpz_setbit(start, bits - 1);
            mpz_setbit(start, 0);

            uint64_t target = (uint64_t)(6 + 4 * c) * POW_Q48_ONE;

            pow_q48_reject_bound(start, target, bound);
            if (mpz_sgn(bound) <= 0) {
                fail("reject_bound produced no bound", "target > 0, start > 0");
                mpz_clears(start, end, bound, NULL);
                continue;
            }

            /* spans from far below to three times the certificate bound.
               The scale comes from target_size() because mpz_get_ui() would
               truncate a Q48 bound on Windows (LLP64) -- and the assertions
               below only require certificate/verdict consistency, so they do
               not depend on which side of the bound a span lands. */
            uint64_t b = pow_q48_target_size(start, target);
            if (b < 16) b = 16;
            uint64_t deltas[6];
            deltas[0] = (b > 8) ? b - 8 : 1;
            deltas[1] = (b > 2) ? b - 2 : 1;
            deltas[2] = b;
            deltas[3] = b + 2;
            deltas[4] = 2 * b;
            deltas[5] = 3 * b;

            for (int k = 0; k < 6; k++) {
                uint64_t span = deltas[k];
                if (span == 0) continue;
                mpz_add_ui(end, start, (uint64_t)span);

                pow_q48_verdict verdict =
                    pow_q48_classify(start, end, target);

                if (pow_q48_span_rejected(span, bound)) {
                    certified++;
                    if (verdict == POW_Q48_ACCEPT) {
                        char d[192];
                        snprintf(d, sizeof(d),
                                 "bits=%u span=%llu bound=%llu target=%llx",
                                 bits, (unsigned long long)span,
                                 (unsigned long long)b,
                                 (unsigned long long)target);
                        fail("certificate rejected an acceptable gap", d);
                    }
                } else {
                    examined++;
                }
            }
            mpz_clears(start, end, bound, NULL);
        }
    }
    gmp_randclear(rs);

    printf("  certificate: %d spans certified (< bound), %d left to examine\n",
           certified, examined);
    if (certified == 0) {
        fail("certificate never fires", "bound too small to be useful");
    }
}

/* ---------------------------------------------------------------------------
 * 4. Fail-open semantics
 * ------------------------------------------------------------------------- */

static void test_fail_open(void) {
    mpz_t start, end, bound;
    mpz_inits(start, end, bound, NULL);

    mpz_set_ui(start, 1000003);
    mpz_set_ui(end, 1000003 + 1000);

    /* No target known -> must examine, never reject. */
    if (pow_q48_classify(start, end, 0) != POW_Q48_UNKNOWN) {
        fail("target=0 must be UNKNOWN", NULL);
    }
    pow_q48_reject_bound(start, 0, bound);
    if (mpz_sgn(bound) != 0) {
        fail("bound must be 0 when the target is unknown", NULL);
    }
    if (pow_q48_span_rejected(1, bound) || pow_q48_span_rejected(1000000, bound)) {
        fail("a 0 bound must never reject", NULL);
    }

    /* Degenerate inputs must not crash or claim a verdict. */
    if (pow_q48_classify(start, end, POW_Q48_ONE) == POW_Q48_UNKNOWN) {
        fail("a real target on a sane gap must classify", NULL);
    }
    mpz_set_ui(start, 0);
    if (pow_q48_classify(start, end, POW_Q48_ONE) != POW_Q48_UNKNOWN) {
        fail("start=0 must be UNKNOWN", NULL);
    }
    if (pow_q48_merit(start, end) != 0 || pow_q48_difficulty(start, end) != 0) {
        fail("start=0 must give 0, not a bogus value", NULL);
    }

    mpz_clears(start, end, bound, NULL);
}

/* ---------------------------------------------------------------------------
 * 5. Header target helper
 * ------------------------------------------------------------------------- */

static void test_header_target(void) {
    uint8_t hdr[80];

    memset(hdr, 0xab, sizeof(hdr));
    uint64_t q48 = ((uint64_t)24 << 48) | 0x1234;
    for (int i = 0; i < 8; i++) {
        hdr[POW_Q48_HEADER_OFFSET + i] = (uint8_t)(q48 >> (8 * i));
    }

    if (pow_q48_target_from_header(hdr) != q48) {
        fail("header target round trip", NULL);
    }
    if (pow_q48_target_from_header(NULL) != 0) {
        fail("NULL header must give 0", NULL);
    }
    if (fabs(pow_q48_readable(q48) - 24.0000000000697) > 1e-9) {
        fail("readable conversion", NULL);
    }
}

/* ---------------------------------------------------------------------------
 * 6. target_size is the inverse of merit
 * ------------------------------------------------------------------------- */
static void test_target_size_inverse(void) {
    static const struct { uint64_t gap; unsigned bits; } cases[] = {
        {1000, 256}, {2000, 512}, {20000, 1024}, {200000, 2048}
    };
    gmp_randstate_t rs;

    gmp_randinit_mt(rs);
    gmp_randseed_ui(rs, 20260924u);

    for (unsigned i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        mpz_t start, end;
        mpz_inits(start, end, NULL);
        mpz_urandomb(start, rs, cases[i].bits);
        mpz_setbit(start, cases[i].bits - 1);
        mpz_setbit(start, 0);
        mpz_add_ui(end, start, (uint64_t)cases[i].gap);

        uint64_t merit = pow_q48_merit(start, end);
        uint64_t span_back = pow_q48_target_size(start, merit);

        if (span_back + 2 < cases[i].gap || span_back > cases[i].gap + 2) {
            char d[160];
            snprintf(d, sizeof(d), "gap=%llu merit=%llx target_size=%llu",
                     (unsigned long long)cases[i].gap,
                     (unsigned long long)merit,
                     (unsigned long long)span_back);
            fail("target_size(merit(gap)) != gap", d);
        }
        mpz_clears(start, end, NULL);
    }
    gmp_randclear(rs);
}

/* ---------------------------------------------------------------------------
 * 7. Span qualification (the decision the resolve gate makes)
 * ------------------------------------------------------------------------- */

static void test_span_qualification(void) {
    static const unsigned kBits[] = {256, 512, 2048};
    gmp_randstate_t rs;
    int certified = 0, qualified = 0;

    gmp_randinit_mt(rs);
    gmp_randseed_ui(rs, 5150u);

    for (unsigned w = 0; w < sizeof(kBits) / sizeof(kBits[0]); w++) {
        unsigned bits = kBits[w];
        for (int c = 0; c < 5; c++) {
            mpz_t start, end, bound;
            mpz_inits(start, end, bound, NULL);
            mpz_urandomb(start, rs, bits);
            mpz_setbit(start, bits - 1);
            mpz_setbit(start, 0);

            uint64_t target = (uint64_t)(8 + 6 * c) * POW_Q48_ONE;            pow_q48_reject_bound(start, target, bound);
            uint64_t b = pow_q48_target_size(start, target);
            if (b < 16) b = 16;

            uint64_t spans[5];
            spans[0] = (b > 4) ? b - 4 : 1;
            spans[1] = b;
            spans[2] = b + 4;
            spans[3] = 2 * b;
            spans[4] = 1;

            for (int k = 0; k < 5; k++) {
                uint64_t span = spans[k];
                int may = pow_q48_span_may_qualify(start, span, target);

                /* The certificate and the span decision must agree, and a
                   "certified" span must never be accepted exactly. */
                if (pow_q48_span_rejected(span, bound)) {
                    certified++;
                    if (may != 0) {
                        fail("rejected span reported as qualifying", NULL);
                    }
                    mpz_add_ui(end, start, (uint64_t)span);
                    if (pow_q48_classify(start, end, target) == POW_Q48_ACCEPT) {
                        fail("certified span was exactly acceptable", NULL);
                    }
                } else {
                    qualified++;
                    if (may == 0) {
                        fail("non-certified span reported as rejected", NULL);
                    }
                }
            }
            mpz_clears(start, end, bound, NULL);
        }
    }
    gmp_randclear(rs);

    printf("  span decision: %d certified, %d must be examined\n",
           certified, qualified);
    if (certified == 0 || qualified == 0) {
        fail("span decision coverage", "one of the two outcomes never occurred");
    }

    /* Fail-open: an unknown target must never certify anything. */
    {
        mpz_t start;
        mpz_init_set_ui(start, 1000003);
        if (pow_q48_span_may_qualify(start, 1, 0) != 1) {
            fail("span decision must fail open without a target", NULL);
        }
        /* A degenerate span must not be certified either (fail open). */
        if (pow_q48_span_may_qualify(start, UINT64_MAX, POW_Q48_ONE) != 1) {
            fail("span decision must fail open on a degenerate span", NULL);
        }
        mpz_set_ui(start, 0);
        if (pow_q48_span_may_qualify(start, 1, POW_Q48_ONE) != 1) {
            fail("span decision must fail open on start=0", NULL);
        }
        mpz_clear(start);
    }
}

int main(int argc, char **argv) {
    const char *path = (argc > 1) ? argv[1] : "tests/data/pow_q48_vectors.txt";

    printf("Q48 arithmetic vs the Gapcoin node implementation\n");
    test_vectors(path);
    test_min_gap_closed_form();
    test_certificate_soundness();
    test_span_qualification();
    test_fail_open();
    test_header_target();
    test_target_size_inverse();

    if (failures == 0) {
        printf("PASS: Q48 arithmetic and interval certificate\n");
        return 0;
    }
    fprintf(stderr, "FAIL: %d checks failed\n", failures);
    return 1;
}
