#!/usr/bin/env bash
# Wait for scripts/mech_sieve_ab.sh to finish, then analyse its arms.
#
# WHY a separate watcher: the experiment runs ~80 min on the GPU and the
# analysis must run on the SAME dumps afterwards, so the pipeline should
# complete by itself instead of depending on someone being at the keyboard.
# The harness writes "all arms done" as its last line.
#
# NOTE: do not edit this file or scripts/mech_sieve_ab.sh while either runs.
set -u
LOG=/tmp/mech_run.log
OUT=/tmp/mech_analysis.txt

for _ in $(seq 1 300); do            # 300 x 30 s = 2.5 h ceiling
    if grep -q "all arms done" "$LOG" 2>/dev/null; then
        break
    fi
    sleep 30
done

{
    echo "=== mech_sieve_analysis  $(date -u +%FT%TZ) ==="
    python3 scripts/mech_sieve_analyze.py
    echo
    echo "=== arm logs: banner + last stats ==="
    for P in 2000 50000 2000000; do
        f="/tmp/mech_P${P}.log"
        [ -f "$f" ] || continue
        echo "--- sieve-primes=$P ---"
        grep -m1 -o 'survivors do not fit.*' "$f" || true
        grep -m1 -o 'window=[0-9]* sieve=[0-9]*' "$f" || true
        grep '\[GAP_HUNT\] k=' "$f" | tail -1 || true
    done
} > "$OUT" 2>&1

echo "watcher: analysis written to $OUT at $(date -u +%T)" >> /tmp/mech_watch.log
