/*
 * Reference oracle for new_src/pow_q48.c.
 *
 * This program links the *Gapcoin node's own* PoWUtils implementation
 * (Gapcoin/src/PoWCore/PoWUtils.cpp, GPL-3.0-or-later) and prints the values
 * that node would compute for a deterministic set of (start, gap) cases.
 * The output is committed as tests/data/pow_q48_vectors.txt and checked by
 * tests/test_pow_q48.c, which is how our port is proven bit-exact instead of
 * merely believed to be.
 *
 * Build (needs a Gapcoin source tree, see scripts/gen_pow_q48_vectors.sh):
 *
 *   g++ -O2 -o pow_q48_oracle tools/pow_q48_oracle.cpp \
 *       "$GAPCOIN_SRC/src/PoWCore/PoWUtils.cpp" \
 *       -I"$GAPCOIN_SRC/src/PoWCore" -lgmpxx -lgmp
 *
 * Usage:
 *   pow_q48_oracle                 # print the committed vector fixture
 *   pow_q48_oracle <start_hex> <gap> <target_hex>
 *                                  # print one ad-hoc case (for debugging)
 *
 * The fixture must stay deterministic: cases are generated from GMP's Mersenne
 * Twister with fixed seeds, so regenerating on another machine reproduces the
 * same file byte for byte.
 */

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

#include <gmp.h>

#include "PoWUtils.h"

static const uint32_t kWidths[] = {256, 512, 1024, 2048};
static const uint32_t kCaseCount = 6;

/* Targets that are close to the difficulty of the generated gaps, so the
   accept/reject boundary is exercised rather than only trivial cases.
   These are merit 10, 22 and 30 in the node's Q48 fixed point
   (10 << 48, 22 << 48, 30 << 48). */
static const char *kTargets[] = {
    /* 10 << 48 = 0xa followed by 12 zeros */
    "000a000000000000",
    /* 22 << 48 = 0x16 followed by 12 zeros */
    "0016000000000000",
    /* 30 << 48 = 0x1e followed by 12 zeros */
    "001e000000000000"
};

static void print_case(PoWUtils &utils, mpz_t start, uint64_t gap,
                       uint64_t target) {
    mpz_t end;
    mpz_init(end);
    mpz_add_ui(end, start, gap);

    uint64_t merit = utils.merit(start, end);
    uint64_t rnd = utils.rand(start, end);
    uint64_t difficulty = utils.difficulty(start, end);
    uint64_t target_size = utils.target_size(start, target);

    /* Note: PoWUtils does not expose min_gap_distance_merit (it is a local of
       difficulty()).  The C test therefore pins our copy of it two ways: the
       identity difficulty == merit + (rand mod min_gap) must hold for every
       vector here (many of which share one start, which forces the modulus),
       and abs(min_gap - 2*2^48/ln(start)) < 2 must hold in closed form. */
    char *start_hex = mpz_get_str(nullptr, 16, start);

    std::printf("%s %llx %llx %llx %llx %llx %llx %d\n",
                start_hex,
                (unsigned long long)gap,
                (unsigned long long)target,
                (unsigned long long)merit,
                (unsigned long long)rnd,
                (unsigned long long)difficulty,
                (unsigned long long)target_size,
                (difficulty >= target) ? 1 : 0);

    free(start_hex);
    mpz_clear(end);
}

int main(int argc, char **argv) {
    PoWUtils utils;

    if (argc == 4) {
        mpz_t start;
        mpz_init_set_str(start, argv[1], 16);
        uint64_t gap = strtoull(argv[2], nullptr, 16);
        uint64_t target = strtoull(argv[3], nullptr, 16);
        print_case(utils, start, gap, target);
        mpz_clear(start);
        return 0;
    }

    std::printf("# Gapcoin Q48 reference vectors, generated by tools/pow_q48_oracle.cpp\n");
    std::printf("# against the node's own src/PoWCore/PoWUtils.cpp.\n");
    std::printf("# start_hex gap_hex target_hex merit rand difficulty target_size valid\n");

    for (uint32_t w = 0; w < sizeof(kWidths) / sizeof(kWidths[0]); w++) {
        uint32_t bits = kWidths[w];
        for (uint32_t t = 0; t < sizeof(kTargets) / sizeof(kTargets[0]); t++) {
            for (uint32_t c = 0; c < kCaseCount; c++) {
                gmp_randstate_t rs;
                gmp_randinit_mt(rs);
                gmp_randseed_ui(rs, 1000003u * (bits + 7u * t + 11u * c) + 17u);

                mpz_t start;
                mpz_init(start);
                mpz_urandomb(start, rs, bits);
                mpz_setbit(start, bits - 1);   /* full length */
                mpz_setbit(start, 0);          /* odd (must be a plausible prime) */
                gmp_randclear(rs);

                /* gaps: a fixed ladder plus one near the target's own scale */
                uint64_t target = strtoull(kTargets[t], nullptr, 16);
                double readable = utils.get_readable_difficulty(target);
                double ln_start = 0.6931471805599453 * (double)(bits - 1);
                uint64_t near = (uint64_t)(readable * ln_start);
                uint64_t gaps[6] = {2, 100, 1000, near, near + 2, near * 2};

                print_case(utils, start, gaps[c % 6], target);
                mpz_clear(start);
            }
        }
    }

    /* Same-start group: one fixed start with many different gaps.  Every case
       shares min_gap_distance_merit, so a wrong modulus in our port cannot
       stay hidden behind a lucky congruent residue. */
    {
        gmp_randstate_t rs;
        gmp_randinit_mt(rs);
        gmp_randseed_ui(rs, 987654321u);

        mpz_t start;
        mpz_init(start);
        mpz_urandomb(start, rs, 1273);
        mpz_setbit(start, 1272);
        mpz_setbit(start, 0);
        gmp_randclear(rs);

        uint64_t target = strtoull(kTargets[1], nullptr, 16);
        for (uint32_t c = 0; c < 20; c++) {
            /* 2 * (1 .. 40000) -> even spans, plus the boundary ladder */
            uint64_t gap = 2u * (1u + 1999u * c);
            print_case(utils, start, gap, target);
        }
        mpz_clear(start);
    }

    return 0;
}
